
import { Token } from "./types";

export const mockTokens: Token[] = [
  // --- New Pairs column ---
  {
    id: "honk",
    name: "HONK",
    symbol: "HONK",
    column: "new_pairs",
    priceUsd: 10_000,          // we'll format to $10K
    marketCapUsd: 19_500,      // -> $19.5K
    fdvUsd: 40_000,
    ageSeconds: 60 * 60,       // 1h
    isBonding: false,
    txCount: 101,
    holders: 26,
    liquidityUsd: 15_000,
    change1mPct: -21,
    change5mPct: 3,
    change1hPct: 3,
    change1dPct: 0,
    chain: "SOL",
    verified: true,
    migratedFrom: null,
    logoUrl: "/images/tokens/honk.png", // or leave undefined
    tagLine: "8YBd...bonk",
  

    // new fields:
    timeLabel: "1h",
    addressLabel: "8YBd...bonk",
    candlesCount: 12,
    trophyCount: 0,
    wins: 0,
    losses: 1,
    fScore: 0.917,
    badges: [
      { id: "b1", label: "21%", tone: "negative", icon: "risk" },
      { id: "b2", label: "3% 4h", tone: "positive", icon: "time" },
      { id: "b3", label: "3%", tone: "positive", icon: "growth" },
      { id: "b4", label: "0%", tone: "neutral" },
      { id: "b5", label: "3%", tone: "ghost", icon: "status" }, 
    ],
  },
  {
    id: "wolves",
    name: "Wolves",
    symbol: "WOLVES",
    description: "Wolverhampton Coi v",
    column: "new_pairs",
    priceUsd: 7000,
    marketCapUsd: 4130,
    fdvUsd: 7000,
    age: "1d",
    ageSeconds: 86400,
    isBonding: false,
    txCount: 156,
    holders: 24,
    replies: 12,
    likes: 0,
    buyCount: 1,
    sellCount: 2,
    ratio: 0.245,
    solAmount: 0,
    liquidityUsd: 3500,
    change1mPct: -24,
    change5mPct: 4,
    change1hPct: 4,
    change6hPct: 4,
    change1dPct: 0,
    chain: "SOL",
    verified: true,
    hasWebsite: true,
    hasTelegram: true,
    hasTwitter: true,
    isKing: true,
    migratedFrom: null,
    logoUrl: "https://ui-avatars.com/api/?name=W&background=f97316&color=fff&size=48&bold=true",
    tagLine: "SuKd...PWTF",
    timeLabel: "1d",
    addressLabel: "SuKd...PWTF",
    candlesCount: 12,
    trophyCount: 0,
    wins: 1,
    losses: 2,
    fScore: 0.856,
    badges: [
      { id: "b1", label: "24%", tone: "negative", icon: "risk" },
      { id: "b2", label: "4%", tone: "positive", icon: "time" },
      { id: "b3", label: "4%", tone: "positive", icon: "growth" },
      { id: "b4", label: "0%", tone: "neutral" },
      { id: "b5", label: "4%", tone: "ghost", icon: "status" },
    ],
  },
  {
    id: "monkey-ai",
    name: "MONKEY AI",
    symbol: "MONKEY",
    description: "Artificial Monkey Intelligence",
    column: "new_pairs",
    priceUsd: 14,
    marketCapUsd: 3980,
    fdvUsd: 14000,
    age: "2s",
    ageSeconds: 2,
    isBonding: false,
    txCount: 82,
    holders: 11,
    replies: 5,
    likes: 3,
    buyCount: 2,
    sellCount: 1,
    ratio: 0.45,
    solAmount: 2,
    liquidityUsd: 3000,
    change1mPct: 15,
    change5mPct: 8,
    change1hPct: 0,
    change6hPct: 0,
    change1dPct: 0,
    chain: "SOL",
    verified: true,
    hasWebsite: true,
    migratedFrom: null,
    logoUrl: "https://ui-avatars.com/api/?name=M&background=3b82f6&color=fff&size=48&bold=true",
    tagLine: "4C1E...pump",
    timeLabel: "2s",
    addressLabel: "4C1E...pump",
    candlesCount: 5,
    trophyCount: 0,
    wins: 0,
    losses: 0,
    fScore: 0.723,
    badges: [
      { id: "b1", label: "15%", tone: "positive", icon: "risk" },
      { id: "b2", label: "8%", tone: "positive", icon: "time" },
      { id: "b3", label: "0%", tone: "neutral" },
      { id: "b4", label: "0%", tone: "neutral" },
    ],
  },
  {
    id: "quarterzip",
    name: "Quarterzip",
    symbol: "QZIP",
    description: "Fashion on chain",
    column: "new_pairs",
    priceUsd: 8,
    marketCapUsd: 3970,
    fdvUsd: 8000,
    age: "5s",
    ageSeconds: 5,
    isBonding: false,
    txCount: 31,
    holders: 2,
    replies: 1,
    likes: 0,
    buyCount: 1,
    sellCount: 0,
    ratio: 0.15,
    solAmount: 1,
    liquidityUsd: 2500,
    change1mPct: 0,
    change5mPct: 0,
    change1hPct: 0,
    change6hPct: 0,
    change1dPct: 0,
    chain: "SOL",
    verified: false,
    hasTwitter: true,
    migratedFrom: null,
    logoUrl: "https://ui-avatars.com/api/?name=Q&background=8b5cf6&color=fff&size=48&bold=true",
    tagLine: "DFQu...pump",
    timeLabel: "5s",
    addressLabel: "DFQu...pump",
    candlesCount: 2,
    trophyCount: 0,
    wins: 0,
    losses: 0,
    fScore: 0.512,
    badges: [
      { id: "b1", label: "0%", tone: "neutral" },
      { id: "b2", label: "0%", tone: "neutral" },
    ],
  },
  {
    id: "pepe-moon",
    name: "Pepe Moon",
    symbol: "PMOON",
    description: "To the moon with Pepe",
    column: "new_pairs",
    priceUsd: 0.012,
    marketCapUsd: 12400,
    fdvUsd: 12000,
    age: "1h",
    ageSeconds: 3600,
    isBonding: true,
    bondingProgressPct: 45,
    txCount: 245,
    holders: 89,
    replies: 34,
    likes: 12,
    buyCount: 5,
    sellCount: 3,
    ratio: 0.67,
    solAmount: 5,
    liquidityUsd: 8900,
    change1mPct: 120,
    change5mPct: 89,
    change1hPct: 45,
    change6hPct: 0,
    change1dPct: 0,
    chain: "SOL",
    verified: false,
    hasWebsite: true,
    hasTwitter: true,
    hasTelegram: true,
    migratedFrom: null,
    logoUrl: "https://ui-avatars.com/api/?name=P&background=22c55e&color=fff&size=48&bold=true",
    tagLine: "8xYz...K3pQ",
    timeLabel: "1h",
    addressLabel: "8xYz...K3pQ",
    candlesCount: 34,
    trophyCount: 2,
    wins: 3,
    losses: 2,
    fScore: 0.945,
    badges: [
      { id: "b1", label: "120%", tone: "positive", icon: "risk" },
      { id: "b2", label: "89%", tone: "positive", icon: "time" },
      { id: "b3", label: "45%", tone: "positive", icon: "growth" },
      { id: "b4", label: "0%", tone: "neutral" },
    ],
  },
  {
    id: "doge-killer",
    name: "Doge Killer",
    symbol: "DOGK",
    description: "The real dog coin",
    column: "new_pairs",
    priceUsd: 0.0089,
    marketCapUsd: 8900,
    fdvUsd: 8900,
    age: "3h",
    ageSeconds: 10800,
    isBonding: false,
    txCount: 156,
    holders: 67,
    replies: 23,
    likes: 8,
    buyCount: 3,
    sellCount: 4,
    ratio: 0.34,
    solAmount: 3,
    liquidityUsd: 6700,
    change1mPct: -15,
    change5mPct: -8,
    change1hPct: 12,
    change6hPct: 8,
    change1dPct: 0,
    chain: "SOL",
    verified: true,
    hasWebsite: true,
    hasTwitter: true,
    migratedFrom: null,
    logoUrl: "https://ui-avatars.com/api/?name=D&background=ef4444&color=fff&size=48&bold=true",
    tagLine: "9Bnm...7TyU",
    timeLabel: "3h",
    addressLabel: "9Bnm...7TyU",
    candlesCount: 23,
    trophyCount: 1,
    wins: 2,
    losses: 3,
    fScore: 0.678,
    badges: [
      { id: "b1", label: "15%", tone: "negative", icon: "risk" },
      { id: "b2", label: "8%", tone: "negative", icon: "time" },
      { id: "b3", label: "12%", tone: "positive", icon: "growth" },
      { id: "b4", label: "8%", tone: "positive", icon: "growth" },
      { id: "b5", label: "0%", tone: "neutral" },
    ],
  },
  // Final Stretch column 
  {
    id: "bcombat",
    name: "BCOMBAT",
    symbol: "BCBT",
    description: "Blender Combat Gaming",
    column: "final_stretch",
    priceUsd: 28,
    marketCapUsd: 1390000,
    fdvUsd: 2800000,
    age: "9m",
    ageSeconds: 540,
    isBonding: true,
    bondingProgressPct: 99.95,
    txCount: 105,
    holders: 84,
    replies: 45,
    likes: 23,
    buyCount: 12,
    sellCount: 8,
    ratio: 0.89,
    solAmount: 12,
    liquidityUsd: 50000,
    change1mPct: -20,
    change5mPct: 12,
    change1hPct: 5,
    change6hPct: 8,
    change1dPct: 15,
    chain: "SOL",
    verified: true,
    hasWebsite: true,
    hasTwitter: true,
    hasTelegram: true,
    hasDiscord: true,
    migratedFrom: null,
    logoUrl: "https://ui-avatars.com/api/?name=B&background=f59e0b&color=fff&size=48&bold=true",
    tagLine: "2Hgf...9KpL",
    timeLabel: "9m",
    addressLabel: "2Hgf...9KpL",
    candlesCount: 45,
    trophyCount: 5,
    wins: 8,
    losses: 5,
    fScore: 0.892,
    badges: [
      { id: "b1", label: "20%", tone: "negative", icon: "risk" },
      { id: "b2", label: "12%", tone: "positive", icon: "time" },
      { id: "b3", label: "5%", tone: "positive", icon: "growth" },
      { id: "b4", label: "8%", tone: "positive", icon: "growth" },
      { id: "b5", label: "15%", tone: "positive", icon: "growth" },
    ],
  },
  {
    id: "bigger-black-pigger",
    name: "BIGGER BLACK PIGGER",
    symbol: "BBP",
    description: "The biggest pigger",
    column: "final_stretch",
    priceUsd: 13,
    marketCapUsd: 51400,
    fdvUsd: 130000,
    age: "15s",
    ageSeconds: 15,
    isBonding: true,
    bondingProgressPct: 74,
    txCount: 21,
    holders: 18,
    replies: 8,
    likes: 4,
    buyCount: 3,
    sellCount: 2,
    ratio: 0.55,
    solAmount: 8,
    liquidityUsd: 42000,
    change1mPct: 75,
    change5mPct: 33,
    change1hPct: 74,
    change6hPct: 40,
    change1dPct: 40,
    chain: "SOL",
    verified: false,
    hasTwitter: true,
    migratedFrom: null,
    logoUrl: "https://ui-avatars.com/api/?name=BBP&background=ec4899&color=fff&size=48&bold=true",
    tagLine: "ChRp...3Nx",
    timeLabel: "15s",
    addressLabel: "ChRp...3Nx",
    candlesCount: 8,
    trophyCount: 0,
    wins: 1,
    losses: 1,
    fScore: 0.634,
    badges: [
      { id: "b1", label: "75%", tone: "positive", icon: "risk" },
      { id: "b2", label: "33%", tone: "positive", icon: "time" },
      { id: "b3", label: "74%", tone: "positive", icon: "growth" },
      { id: "b4", label: "40%", tone: "positive", icon: "growth" },
      { id: "b5", label: "40%", tone: "positive", icon: "growth" },
    ],
  },
  {
    id: "moon-rocket",
    name: "Moon Rocket",
    symbol: "MRKT",
    description: "Launching to the moon",
    column: "final_stretch",
    priceUsd: 0.45,
    marketCapUsd: 450000,
    fdvUsd: 450000,
    age: "2h",
    ageSeconds: 7200,
    isBonding: true,
    bondingProgressPct: 89,
    txCount: 567,
    holders: 234,
    replies: 89,
    likes: 45,
    buyCount: 15,
    sellCount: 10,
    ratio: 0.78,
    solAmount: 15,
    liquidityUsd: 120000,
    change1mPct: 45,
    change5mPct: 23,
    change1hPct: 18,
    change6hPct: 34,
    change1dPct: 0,
    chain: "SOL",
    verified: true,
    hasWebsite: true,
    hasTwitter: true,
    hasTelegram: true,
    migratedFrom: null,
    logoUrl: "https://ui-avatars.com/api/?name=MR&background=06b6d4&color=fff&size=48&bold=true",
    tagLine: "5Qwx...BnHj",
    timeLabel: "2h",
    addressLabel: "5Qwx...BnHj",
    candlesCount: 89,
    trophyCount: 12,
    wins: 15,
    losses: 10,
    fScore: 0.923,
    badges: [
      { id: "b1", label: "45%", tone: "positive", icon: "risk" },
      { id: "b2", label: "23%", tone: "positive", icon: "time" },
      { id: "b3", label: "18%", tone: "positive", icon: "growth" },
      { id: "b4", label: "34%", tone: "positive", icon: "growth" },
      { id: "b5", label: "0%", tone: "neutral" },
    ],
  },
  {
    id: "shiba-inu-2",
    name: "Shiba Inu 2.0",
    symbol: "SHIB2",
    description: "Next gen Shiba",
    column: "final_stretch",
    priceUsd: 0.000089,
    marketCapUsd: 89000,
    fdvUsd: 89000,
    age: "6h",
    ageSeconds: 21600,
    isBonding: true,
    bondingProgressPct: 92,
    txCount: 789,
    holders: 456,
    replies: 123,
    likes: 67,
    buyCount: 20,
    sellCount: 15,
    ratio: 0.91,
    solAmount: 20,
    liquidityUsd: 67000,
    change1mPct: 234,
    change5mPct: 156,
    change1hPct: 89,
    change6hPct: 67,
    change1dPct: 45,
    chain: "SOL",
    verified: false,
    hasWebsite: true,
    hasTwitter: true,
    migratedFrom: null,
    logoUrl: "https://ui-avatars.com/api/?name=SHIB&background=f97316&color=fff&size=48&bold=true",
    tagLine: "7Kmn...PqRs",
    timeLabel: "6h",
    addressLabel: "7Kmn...PqRs",
    candlesCount: 123,
    trophyCount: 25,
    wins: 20,
    losses: 12,
    fScore: 0.967,
    badges: [
      { id: "b1", label: "234%", tone: "positive", icon: "risk" },
      { id: "b2", label: "156%", tone: "positive", icon: "time" },
      { id: "b3", label: "89%", tone: "positive", icon: "growth" },
      { id: "b4", label: "67%", tone: "positive", icon: "growth" },
      { id: "b5", label: "45%", tone: "positive", icon: "growth" },
    ],
  },

  // Migrated column 
  {
    id: "rwe",
    name: "RWE",
    symbol: "RWE",
    description: "Real World Economy",
    column: "migrated",
    priceUsd: 29,
    marketCapUsd: 86600,
    fdvUsd: 290000,
    age: "0s",
    ageSeconds: 0,
    isBonding: false,
    txCount: 206,
    holders: 94,
    replies: 56,
    likes: 34,
    buyCount: 25,
    sellCount: 18,
    ratio: 0.72,
    solAmount: 25,
    liquidityUsd: 60000,
    change1mPct: -59,
    change5mPct: 0,
    change1hPct: -48,
    change6hPct: -23,
    change1dPct: 6,
    chain: "SOL",
    verified: true,
    hasWebsite: true,
    hasTwitter: true,
    hasTelegram: true,
    migratedFrom: "Old RWE",
    logoUrl: "https://ui-avatars.com/api/?name=R&background=10b981&color=fff&size=48&bold=true",
    tagLine: "HNXQ...pump",
    timeLabel: "0s",
    addressLabel: "HNXQ...pump",
    candlesCount: 56,
    trophyCount: 8,
    wins: 12,
    losses: 8,
    fScore: 0.845,
    badges: [
      { id: "b1", label: "59%", tone: "negative", icon: "risk" },
      { id: "b2", label: "0%", tone: "neutral" },
      { id: "b3", label: "48%", tone: "negative", icon: "growth" },
      { id: "b4", label: "23%", tone: "negative", icon: "growth" },
      { id: "b5", label: "6%", tone: "positive", icon: "growth" },
    ],
  },
  {
    id: "jem",
    name: "Jem",
    symbol: "JEM",
    description: "The precious gem",
    column: "migrated",
    priceUsd: 7,
    marketCapUsd: 28300,
    fdvUsd: 70000,
    age: "2s",
    ageSeconds: 2,
    isBonding: false,
    txCount: 22,
    holders: 101,
    replies: 12,
    likes: 7,
    buyCount: 8,
    sellCount: 6,
    ratio: 0.48,
    solAmount: 8,
    liquidityUsd: 15000,
    change1mPct: 8,
    change5mPct: 0,
    change1hPct: -76,
    change6hPct: -45,
    change1dPct: 76,
    chain: "SOL",
    verified: false,
    hasTwitter: true,
    migratedFrom: "Jem V1",
    logoUrl: "https://ui-avatars.com/api/?name=J&background=a855f7&color=fff&size=48&bold=true",
    tagLine: "6v6A...AqDG",
    timeLabel: "2s",
    addressLabel: "6v6A...AqDG",
    candlesCount: 12,
    trophyCount: 1,
    wins: 2,
    losses: 3,
    fScore: 0.612,
    badges: [
      { id: "b1", label: "8%", tone: "positive", icon: "risk" },
      { id: "b2", label: "0%", tone: "neutral" },
      { id: "b3", label: "76%", tone: "negative", icon: "growth" },
      { id: "b4", label: "45%", tone: "negative", icon: "growth" },
      { id: "b5", label: "76%", tone: "positive", icon: "growth" },
    ],
  },
  {
    id: "safe-moon-v2",
    name: "SafeMoon V2",
    symbol: "SFM2",
    description: "Safely to the moon",
    column: "migrated",
    priceUsd: 0.00156,
    marketCapUsd: 156000,
    fdvUsd: 156000,
    age: "1d",
    ageSeconds: 86400,
    isBonding: false,
    txCount: 1234,
    holders: 678,
    replies: 234,
    likes: 123,
    buyCount: 45,
    sellCount: 34,
    ratio: 0.85,
    solAmount: 45,
    liquidityUsd: 98000,
    change1mPct: -12,
    change5mPct: -8,
    change1hPct: 23,
    change6hPct: 34,
    change1dPct: 45,
    chain: "SOL",
    verified: true,
    hasWebsite: true,
    hasTwitter: true,
    hasTelegram: true,
    hasDiscord: true,
    migratedFrom: "SafeMoon V1",
    logoUrl: "https://ui-avatars.com/api/?name=SFM&background=14b8a6&color=fff&size=48&bold=true",
    tagLine: "3Xyz...Mn9K",
    timeLabel: "1d",
    addressLabel: "3Xyz...Mn9K",
    candlesCount: 234,
    trophyCount: 45,
    wins: 30,
    losses: 20,
    fScore: 0.912,
    badges: [
      { id: "b1", label: "12%", tone: "negative", icon: "risk" },
      { id: "b2", label: "8%", tone: "negative", icon: "time" },
      { id: "b3", label: "23%", tone: "positive", icon: "growth" },
      { id: "b4", label: "34%", tone: "positive", icon: "growth" },
      { id: "b5", label: "45%", tone: "positive", icon: "growth" },
    ],
  },
  {
    id: "elonmars",
    name: "ElonMars",
    symbol: "EMARS",
    description: "Mars colonization token",
    column: "migrated",
    priceUsd: 0.089,
    marketCapUsd: 89000,
    fdvUsd: 89000,
    age: "3d",
    ageSeconds: 259200,
    isBonding: false,
    txCount: 456,
    holders: 234,
    replies: 89,
    likes: 45,
    buyCount: 23,
    sellCount: 19,
    ratio: 0.68,
    solAmount: 23,
    liquidityUsd: 56000,
    change1mPct: 67,
    change5mPct: 45,
    change1hPct: 23,
    change6hPct: 34,
    change1dPct: 56,
    chain: "SOL",
    verified: true,
    hasWebsite: true,
    hasTwitter: true,
    migratedFrom: "ElonMars V1",
    logoUrl: "https://ui-avatars.com/api/?name=EM&background=dc2626&color=fff&size=48&bold=true",
    tagLine: "8Klm...Qr4T",
    timeLabel: "3d",
    addressLabel: "8Klm...Qr4T",
    candlesCount: 89,
    trophyCount: 15,
    wins: 18,
    losses: 12,
    fScore: 0.887,
    badges: [
      { id: "b1", label: "67%", tone: "positive", icon: "risk" },
      { id: "b2", label: "45%", tone: "positive", icon: "time" },
      { id: "b3", label: "23%", tone: "positive", icon: "growth" },
      { id: "b4", label: "34%", tone: "positive", icon: "growth" },
      { id: "b5", label: "56%", tone: "positive", icon: "growth" },
    ],
  },
];
